### ISSUE TITLE
Unreleased D3DPOOL_DEFAULT resources prevents alt-tabbing back into the game

### ISSUE THREAD

**Issue by stk25x** [Alenett/TES-Reloaded-Source#1]
Decided to try looking into why OR gives a blackscreen when alt-tabbing back into Oblivion, this led me down a path of DirectX APIs which I'm not really that familiar with, so forgive me if anything here is incorrect :x

Eventually I learned that when alt-tabbing out of the game this causes the DX9 device to be "lost", with the only way to recover it being to call IDirect3DDevice9::Reset, which the game does do.

Apparently though Reset will only succeed if all D3DPOOL_DEFAULT resources are released before calling it (https://msdn.microsoft.com/en-us/library/bb174714(v=vs.85).aspx, "Responding to a lost device")

OR seems to create some textures/buffers under that pool with no code to release them before calling Reset though (and also uses IDirect3DDevice9::CreateRenderTarget which apparently needs to be released first too)

As a test I commented out the D3DPOOL_DEFAULT resources that are created (+ refs to them), and the CreateRenderTarget call used if "SettingHDR == 1 && SettingMultiSample >= 2", and this allowed Oblivion to reset properly, and alt-tabbing seems to "work" again.

Unfortunately it seems most of these resources are created during initialization of some classes, and would probably need some kind of refactor so that they can be created/destroyed when needed, I'd like to try working on it myself but I'm not familiar with the codebase at all, and you'd probably know what you're doing a lot better than me :P

This alt+tab issue is probably one of the only main complains I have with OR, other than that it's one of the best OB mods imo, hope you can find a way to fix this and make it even better :)

EDIT: also sorry for bugging you if you already knew about this! I just thought that this small alt+tab issue probably wouldn't be much of a priority, so I decided to look into it myself, disregard what I wrote if you already know about it though :)

**Comment by Alenett** [comment]
Hi there.
Thank you for your contribution but the blackscreen is not an OR problem. Oblivion does that in the vanilla game. It should be fix in Oblivion. If you want to use the alt-tab, you have to set bfullscreen=0 in your Oblivion.ini. OR will automatically remove the window border and you can play at full screen and use the alt-tab.

Cheers.

⁣Inviato da BlueMail ​

Il giorno 3 Ago 2017, 05:50, alle ore 05:50, stk25x <notifications@github.com> ha scritto:

**Comment by Alenett** [comment]
Hi there. 

Thank you for your contribution but the blackscreen is not an OR problem. Oblivion does that in the vanilla game. It should be fix in Oblivion. If you want to use the alt-tab, you have to set bfullscreen=0 in your Oblivion.ini. OR will automatically remove the window border and you can play at full screen and use the alt-tab. 

Cheers.

⁣Inviato da BlueMail ​

Il giorno 3 Ago 2017, 05:50, alle ore 05:50, stk25x <notifications@github.com> ha scritto:
